#!/bin/sh
# vim:fdm=marker

# core {{{

alias \
  bc="bc -w -q" \
  cp="cp -v" \
  ls="ls --color" \
  md="mkdir -p" \
  mv="mv -v" \
  rm="rm -v" \
  sed="sed --posix"
cd() {
  builtin cd "$@" && ls
}

alias \
  sus="systemctl suspend" \
  reboot="doas reboot" \
  shutdown="doas shutdown -h now"

alias \
  pq="nix search nixpkgs --offline"

# }}}

# common {{{

alias \
  am="amfora" \
  g="git" \
  hack="nethack" \
  lofi="pl https://youtu.be/jfKfPfyJRdk" \
  n="newsboat" \
  nr="doas nixos-rebuild" \
  pl="mpv --terminal" \
  search="w3m google.com" \
  server="${HOME}/Data/Code/server.sh" \
  sp="ncspot" \
  ss="sc-im" \
  zr=". ${ENV}"

# }}}

# navigation {{{

fm() {
  fm="$(mktemp)"
  vifm --choose-dir="$fm"
  dir="$(cat "$fm" | tr ' ' '\ ')"
  rm -f "$fm" > "/dev/null"
  cd "$dir"
}
alias r="fm"

b() {
  bookmarkFile="${XDG_DATA_HOME}/sh/bookmarks"

  md "$(dirname "$bookmarkFile")"
  ! test -f "$bookmarkFile" && \
    touch "$bookmarkFile"
  if [ -n "$1" ]; then
    $EDITOR "$bookmarkFile"
    return
  fi
  bpath="$(cat "$bookmarkFile" | \
    fzf | \
    cut -d ',' -f 2)"
  bpath="$(eval "echo $bpath")"

  if ! test -e "$bpath"; then
    echo \
"Error: invalid bookmark.
Add new bookmarks to ${bookmarkFile}
with the format 'identifier, path'"
  else
    cd "$bpath"
  fi
}

rp() {
  md "$XDG_REPO_HOME"
  repo="$(ls --color=no "$XDG_REPO_HOME" | fzf)"
  cd "${XDG_REPO_HOME}/${repo}"
}

# }}}

# environments {{{

alias \
  ns="nix-shell ${DOTDIR}/user/shells/hacking.nix"

# }}}

# security {{{

pwgen() {
  tr -dc "[:alnum:]" < /dev/urandom | fold -w 50 | head -n 25 | sed 's/.\{10\}/& /g'
}

ge() {
  gpg --encrypt --sign --armor --default-recipient-self "$1"
  mv "./${1}.asc" "$1"
}
gd() {
  gpg --output "$1" --yes --decrypt "$1"
}

# }}}

# media {{{

alias \
  ytmp3="yt-dlp -x --audio-format mp3" \
  ytmp4="yt-dlp"

# }}}

# misc {{{

ch() {
  swaymsg input type:pointer events disabled
  swaymsg input type:touchpad events disabled
}

cs() {
  swaymsg input type:pointer events enabled
  swaymsg input type:touchpad events enabled
}

# }}}
