#!/bin/sh

# prevent GTK apps from taking forever to load (pavucontrol)
systemctl --user import-environment
# background
swaybg -c "#292E39" &
# status bar
waybar &
# notification/update bar
mkfifo "$WOBSOCK"
tail -f "$WOBSOCK" | wob &
